### ISSUE TITLE
Publish the last version on VS Code Extensions marketplace

### ISSUE THREAD

**Issue by Greybird** [ecirpnaes/SimpleDataScripter#10]
Hello,

It seems the last version of the extension, which fixes the culture issue of the export, is not available in VS Code extensions marketplace.
Could you please publish it ?

Thanks

**Comment by ecirpnaes** [comment]
You're correct. I just did a PR to the release/extensions branch of Azure Data Studio, so it should get updated next time MS does an Azure update. For reference, there is no automated way to publish an extension to Azure Data Studio. You have to edit a gallery file hosted by the ADS team and submit a pull request. Once it's approved, they merge it into the release branch. Not sure why they don't make it as simple as publishing Visual Code extensions, but it is what it is.

**Comment by Greybird** [comment]
Thanks a lot!
