### ISSUE TITLE
Generating INSERT statements for columns of type VARBINARY(MAX) default to null.

### ISSUE THREAD

**Issue by MorneAppenate** [ecirpnaes/SimpleDataScripter#14]
When generating INSERT statements for columns of type VARBINARY(MAX), the extension just returns null for those columns. This effectively results in the data contained within that column to be lost.

It is very easy to replicate:
1. Create a table containing a column of type VARBINARY(MAX).
2. Right-click on the table, select **Script Table Data** and then select press **Enter** to accept the default SQL.
3. You'll see in the output, that the data for VARBINARY(MAX) has been replaced with null.

**Comment by ecirpnaes** [comment]
That is correct. It is by design, and documented in the "Known Issues"
section of the README.That said, support for varbinary data will likely be
included in an upcoming release.

**Comment by ecirpnaes** [comment]
This functionality has been added and is now available in release version: v0.1.6
