### ISSUE TITLE
Spatial objects do not import

### ISSUE THREAD

**Issue by mecgit** [ecirpnaes/SimpleDataScripter#2]
When a spatial object is exported, the extension encloses the spatial Well-Known-Binary (WKB) representation of the shape in single quotes.  The shape will not round-trip as SQL assumes that a string inserted into a spatial column will contain the Well-Known-Text (WKT) representation not the WKB.

Fix by removing the single quotes on the output of spatial columns.

**Comment by ecirpnaes** [comment]
Added partial support for Spatial Objects in v0.1.3
