### ISSUE TITLE
it's can't install 

### ISSUE THREAD

**Issue by KesharaWaidyarathna** [ecirpnaes/SimpleDataScripter#5]
![image](https://user-images.githubusercontent.com/45634700/79944466-31da5680-8489-11ea-85d0-13a50a77ab8a.png)

![image](https://user-images.githubusercontent.com/45634700/79944504-4e768e80-8489-11ea-99a7-c34cbb8cbbb5.png)

**Comment by ecirpnaes** [comment]
n/a
