### ISSUE TITLE
Support for MFA authentication

### ISSUE THREAD

**Issue by Greybird** [ecirpnaes/SimpleDataScripter#9]
Hello,

When using with a database where MFA is used, I get the following error:
>Scripting Data for : [DB].[Schema].[Table] : Query has no results to return

However, when I connect to the same database using a SQL account, it works like a charm.
Do you have any idea on how to fix this ?

**Comment by ecirpnaes** [comment]
Connecting with MFA was something I never even considered. I'll add that to the task to look into.

**Comment by ecirpnaes** [comment]
Fixed by Greybird
